name: concurrency

on:
    [workflow_dispatch,push]

jobs:
    first:
        runs-on: ubantu-latest
        steps:
        - name: first job
          run: 
            echo "sleep for 10 second"
            sleep 10
    second:
        runs-on: ubantu-latest
        needs: first
        steps:
        - name: second job 
          run: |
            echo "sleep for 600 second"
            sleep 600s   

          