name: Generate ASCII Artwork

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v6
        
        - name: Install cowsey program
          run: sudo apt-get install cowsay -y
       
        - name: Execute cowsey cmd 
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

        - name: Test file exists
          run: grep -irn "dragon" dragon.txt
        
        - name: Read file
          run: cat dragon.txt
        
        - name: list repo files
          run: ls -ltra

