name: Exploring variable and secret

on: push

env: 
             WORKFLOW_ENV: workflow_env
jobs: 
    job_1:
        env: 
             JOB_ENV: job_env
        runs-on: ubuntu-latest
        steps:  
        - name: print variables
          env: 
             STEP_ENV: step_env
          run: echo $STEP_ENV | $JOB_ENV | $WORKFLOW_ENV
    job_2:
        env: 
             JOB_ENV: job_env_2
        runs-on: ubuntu-latest
        steps:  
        - name: print variables 2
          env: 
             STEP_ENV: step_env_2
          run: echo $STEP_ENV | $JOB_ENV | $WORKFLOW_ENV
    job_3:
        env: 
             JOB_ENV: job_env_3
        runs-on: ubuntu-latest
        steps:  
        - name: print variables 3
          env: 
             STEP_ENV: step_env_3
          run: echo $STEP_ENV | $JOB_ENV | $WORKFLOW_ENV | ${{secrets.TEST_PASSWORD}} | ${{vars.TEST_VARIABLE}}